import json
import glob
from constants import ANNOTATION_GLOB, ANNOTATION_PATH

"""
This function is used to combine multiple annotations generated by VIA allowing
collaboration in the data annotation process.
"""


def combine_data(paths, out_file):
    files = glob.glob(paths)
    data = {}
    for file in files:
        with open(file) as fp:
            data.update(json.load(fp))
    with open(out_file, "w") as fp:
        return json.dump(data, fp)


if __name__ == "__main__":
    combine_data(ANNOTATION_GLOB, ANNOTATION_PATH)
