image: gitpod/workspace-full-vnc
tasks:
  - name: Setup
    before: sudo apt-get update && sudo apt-get install ffmpeg libsm6 libxext6  -y
    command: pip install -r requirements.txt

  - name: "Download coco weights"
    before: |
      cd data/
    command: |
      wget --no-clobber https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5

# # Ports to expose on workspace startup
ports:
  - port: 5901
    name: VNC Connection
    description: Connect to Remote Display. Use TightVNC.
